### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by NextBlaubeere** [RobinLinus/snapdrop#153]
Ok, since there is a Desktop Application for this, wouldn't it make sense to also do a Android App?
Ideally with option for "always on in background" so you do not have to type the url into the browser.

also firefox focus (the browser on our family-tablet) is not downloading any files ... would help with that too i guess :-)

**Comment by PaulSzymanski** [comment]
Snapdrop is a Progressive Web App (PWA). On supporting browsers, you can 'install' the PWA without the need of a native app. This feature is called Add to home screen (A2HS).

A2HS is supported in all mobile browsers. It's also supported in some Chromium desktop browsers (that includes Chrome and Edge). List of supporting browsers: https://caniuse.com/#feat=web-app-manifest

The Desktop App is for people that do not want to install/use Chrome/Edge on Desktop. Since A2HS is supported by all mobile browsers there is no need for an Android App. Because of this and more importantly because native apps are out of scope of this project I am closing this issue. But, feel free to create an Android App by yourself; no one will stop you ;)

The broken file download is most likely related to this issue: https://github.com/mozilla-mobile/focus-android/issues/804. Not sure if we can do anything about it.

Btw, file uploads don't work as well: https://github.com/mozilla-mobile/focus-android/issues/937.

**Comment by NextBlaubeere** [comment]
Thank you for your detailed explanation about the firefox-focus incompatibility and also your statement about A2HS. I was not aware of that feature and I am going to try this. :-)

**Comment by child-duckling** [comment]
Also, #156
