### ISSUE TITLE
Snapdrop Shows Itself

### ISSUE THREAD

**Issue by Bellisario** [RobinLinus/snapdrop#215]

**Comment by Bellisario** [comment]
![Problem](https://user-images.githubusercontent.com/72039923/103032913-7c086000-4561-11eb-8c30-46359088313c.png)

View the name of the peer and the other...
I opened Snapdrop in two windows and it view itself...

**Comment by RobinLinus** [comment]
This is actually a much deeper issue. Snapdrop works only in a single tab. 
Once you open it in another tab the new tab overwrites the server connection of the old tab. And the old tab becomes somewhat of a zombie mode because it can call the server, but the server will send all messages addressed to this user to the new tab. 

So, the real solution here is to kill the old tab when you open Snapdrop in a new tab. That requires to check if a download is going on and react accordingly.

**Comment by Bellisario** [comment]
Thank you @RobinLinus
