### ISSUE TITLE
snapdrop can't recognize devices using VPN actually in the same local network.

### ISSUE THREAD

**Issue by tyn1998** [RobinLinus/snapdrop#251]
Dear developers,

Thank you for providing such an elegant  cross-platform local network file transition tool!

I am a VPN user, which means I always turn my proxy on in all devices. So when I first try this tool, I find it doesn't work. Then I realize maybe I should turn my proxy off and try again. After that, all my devices icon show up in the browser. So I want to ask if you can consider this situation into this elegant tool to make it smarter.

Thanks again!

**Comment by fm-sys** [comment]
We've had a lot of requests for VPN. Unfortunately, I have to tell you that it is not possible due to the architecture of snapdrop. The devices must have the public IP address in order to be able to find each other. And the goal of a VPN is to hide the IP from the outside world... Unfortunately (or perhaps fortunately from a data protection perspective 😉) we can't do anything about it!

**Comment by tyn1998** [comment]
Got it！ Thanks for your answer.
