### ISSUE TITLE
Send multiple Files at once

### ISSUE THREAD

**Issue by momongithub** [RobinLinus/snapdrop#264]
I didnt find any possibility to send more than 1 file from my Windows PC to my iPad. Although you can select multiple files, i only receive the last one i have selected.

**Comment by Ramalama2** [comment]
This would be actually awesome to drop a whole folder inside.

**Comment by Bben01** [comment]
@Ramalama2 It's really hard to implement this feature because there isn't one unique standard between all platforms for drag and dropping folders

**Comment by Ramalama2** [comment]
> @Ramalama2 It's really hard to implement this feature because there isn't one unique standard between all platforms for drag and dropping folders

Yeah, you have right, i seen the same with nextcloud, if you drop a folder into it.

But on the other side there are now only 3 browsers left: edge(chrome) / chrome / firefox
And mobile devices, doesn't even offer an option to share multiple files 😂

Even if you make it work between those 3 browsers, it would be cool.
Then if you drop multiple files/folder from pc to mobile device, there could be a popup (mobile devices doesn't support multiple files)

And in the end the biggest issue is, if i drop a folder to another pc, how does the other pc download it?
Since downloads works only for one file.
Probably this is the issue that breaks the whole idea 🤦‍♂️

However, close this thread if there is no solution. I mean if something isn't possible, it isn't possible 😂

Cheers & thx for reply!

**Comment by momongithub** [comment]
Hey guys, so I found kind of a solution to transfer files from a windows pc to your ios/ipados device yesterday: just select all the files you want to transfer on your windows pc, rightclick, send to, compressed zip file. now you have all your files in a zip file, which you actually can transfer to your device since iphones and ipads can unzip them.

**Comment by stephane-archer** [comment]
it's a nice workaround but I would love to see the multi-file sharing feature.
@Bben01 can't we just support one standard?
I'm fine switching to chrome or firefox when I want to send multiple files.
