### ISSUE TITLE
Selfhosted doesn't work on bromite

### ISSUE THREAD

**Issue by Robin-Sch** [RobinLinus/snapdrop#326]
Both uploading and downloading doesn't work in bromite, in other browser(s) it does.

OS: LineageOS 17.1

**Comment by Robin-floss** [comment]
On mull it doesn't work either, but I at least get an error
![image](https://user-images.githubusercontent.com/46354497/125111473-3dde2280-e0e6-11eb-834f-276898a243d2.png)

**Comment by watermelonpizza** [comment]
Just did some investigation, in mull and potentially any other security enhanced browsers, they will have WebRTC disabled.

To enable it back in mull and other Firefox-like browsers set `media.peerconnection.enabled` to `true` in `about:config`. Of course, you're defeating the purpose of it being off in the first place so enabling it is personal security preference, I guess.

Otherwise you could toggle this setting every time you want to use snapdrop. A little inconvenient, but something which could be done.

**Comment by Robin-Sch** [comment]
> Otherwise you could toggle this setting every time you want to use snapdrop. A little inconvenient, but something which could be done.

Or a different profile, then you can still have it disabled on "normal" sites and have a separate profile for snapdrop only. Without having to toggle it every time.

**Comment by watermelonpizza** [comment]
> Or a different profile, then you can still have it disabled on "normal" sites and have a separate profile for snapdrop only

Though this isn't possible on android. Could install multiple editions of the browser.
