### ISSUE TITLE
Flatpak package on Flathub

### ISSUE THREAD

**Issue by alexanderadam** [RobinLinus/snapdrop#473]
It would be nice if [SnapDrop would be available on FlatHub](https://flathub.org/apps/search/SnapDrop).
It seems that there is some official documentation on this:

- https://docs.flatpak.org/en/latest/electron.html
- https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app

**Comment by Bellisario** [comment]
I don't think this is possible since Snapdrop is a Web Application and not an Application.
Your documentation links refer to an Electron app, but Snapdrop isn't.

You can easily access Snaprop on https://snapdrop.net/ or by installing it as a Web App from the same site and opening like any other application.

Anyway, if you instead was referring to the Server, you can install it using this Docker guide: https://github.com/RobinLinus/snapdrop/blob/master/docs/local-dev.md

**Comment by alexanderadam** [comment]
Okay, then I'll close this issue here.
I just thought that it'd be possible to spin up a server with an embedded browser/webview pointing to it.
But I guess a regular Docker image is doing fine as well.
