### ISSUE TITLE
snapdrop.net is down

### ISSUE THREAD

**Issue by domhof** [RobinLinus/snapdrop#51]
snapdrop.net seems to be down right now.

**Comment by alexwhittemore** [comment]
Basically always ;)

**Comment by dmo-odoo** [comment]
Still down as of now.

**Comment by frafrichile** [comment]
Still down.  What is going on ?

**Comment by kurtextrem** [comment]
Maybe put it on Github Pages?

**Comment by alexwhittemore** [comment]
Github pages only hosts static content, not server-side applications. So that's not suitable for hosting the signalling server.

The problem here is that any solution would cost @domhof money proportional to how many people use the service, so as a side project proof of concept, it's probably not going to happen. The best solution is probably to install it yourself on the free tier of whatever app server you can find. I'm guessing that's what he's done, but it won't scale to many users.

**Comment by Thomvh** [comment]
I´ve started to host direct copy of the github repository on my own dedicated server. See http://drop.t97.nl/

**Comment by dmo-odoo** [comment]
Hello @Thomvh, and thank you ! I tried to do the same on heroku but never managed to make it run properly. Still not sure if I was doing something wrong or if I hit a limitation of Heroku. In any case, you might want to remove the "yg.gl" short link on the front page, since it redirects to the old page.

**Comment by Thomvh** [comment]
I know. I still need to remove that!

Op 22 aug. 2017 14:11 schreef "David Monjoie" <notifications@github.com>:

**Comment by TitanNano** [comment]
@Thomvh I can't get any files through. it always says sending... and downloading... even though the file is 2kb in size.

**Comment by Thomvh** [comment]
Weird... It worked fine for me today. But I will look into it!

Op 10 sep. 2017 22:34 schreef "Jovan Gerodetti" <notifications@github.com>:

**Comment by ayunami2000** [comment]
I got the Plesk default index page

**Comment by douglasduteil** [comment]
Hi there 
We forked Snapdrop at https://onedoes.github.io/snapdrop
We are willing to maintain it at https://github.com/onedoes/snapdrop
See you :)

**Comment by RobinLinus** [comment]
up again http://snapdrop.net :)
