### ISSUE TITLE
Feature Req: Add disable animation toggle

### ISSUE THREAD

**Issue by foundObjects** [RobinLinus/snapdrop#522]
Low priority request here: It would be nice to have a "no animations" or similar toggle to make the app a bit friendlier for e-ink displays. Even just disabling the ripple animation on the main screen would be great, that screen makes my e-reader a bit sad.

Cheers and thanks!

**Comment by Bellisario** [comment]
I don't think another button would be a good solution because of the Snapdrop simplicity that must be kept (ex. https://github.com/RobinLinus/snapdrop/pull/214#issuecomment-750461283).

It's also written here:\
https://github.com/RobinLinus/snapdrop/blob/master/docs/faq.md#why-dont-you-implement-feature-xyz

---

The thing can be done for sure it's to check if the device used is an e-readed (probably using UserAgent) or not, and enable the background animation with this logic.

I could try to implement something, but I want first @RobinLinus to give a feedback about this.

**Comment by RobinLinus** [comment]
yes, maybe someone wants to create a fork. We can link to it in our FAQ.
