### ISSUE TITLE
Win10 to iPad (12.2) Files Fail to Send

### ISSUE THREAD

**Issue by WoodyATX** [RobinLinus/snapdrop#92]
Running on Windows 10 and IOS 12.2 (on an iPad).  Using Safari on iPad and I have tried Chrome, Firefox and Microsoft Edge web browsers on Win 10 and see the same problem on all browsers.

Looking at the console in Chrome I see the following error  message when a file is selected to be transfered and SnapDrop shows "Transferring..." but the progress bar never moves:

```
network.js:392 Uncaught TypeError: Cannot read property 'sendFiles' of undefined
    at PeersManager._onFilesSelected (network.js:392)
    at network.js:361
    at Function.fire (network.js:499)
    at PeerUI._onFilesSelected (ui.js:117)
    at HTMLInputElement.<anonymous> (ui.js:82)
_onFilesSelected @ network.js:392
```

Both the Win10 computer and iPad are on the same wireless network.

**Comment by Niush** [comment]
Same Problem Here
![image](https://user-images.githubusercontent.com/16359077/86265278-4bafbc80-bbe3-11ea-80de-eb8d4eaa296a.png)

![image](https://user-images.githubusercontent.com/16359077/86265338-6124e680-bbe3-11ea-869c-c77c7ad8c4f2.png)

And also a lots of 500 Internal Server Errors (especially after service worker is installed not on first run)

**Comment by PaulSzymanski** [comment]
The issue was very likely coming from a to strict limit on open file descriptors for nginx and is not specific to the user agent. I have increased it now. I hope this will suffice. A major problem is that connections to the server are kept alive. This obviously does not scale well. We might have to be more smart about it. Maybe only keeping the connection alive if the browser window is active or something similar.
Thanks for opening the issue! Feel free to comment again or open a new issue if the problem persists.

**Comment by schadenn** [comment]
Still having this issue...

Chrome 87.0.4280.88 on Windows 10 <-> Chrome 83.0.4103.106 on Android EMUI 10.1.0
