### ISSUE TITLE
Snapdrop.net down?

### ISSUE THREAD

**Issue by aagha** [RobinLinus/snapdrop#99]
I was trying to show my cousin Snapdrop yesterday but found the site to be down. Is it down for good?

**Comment by jakesta12** [comment]
Snapdrop.net it’s down not working. ???

**Comment by mtratchet16** [comment]
I've also been having trouble the past few days. I really wish they had some sort of social media (like Twitter) so we can contact them directly instead of waiting and hoping they view these comments. I've suffered a tremendous loss to productivity due to this.

**Comment by Strath1** [comment]
Snapdrop has also stopped working for me over the last week. This tool was AMAZING and I would love to continue using it!

**Comment by mtratchet16** [comment]
I tweeted the Robin Linus who I'm guessing is in charge of Snapdrop since the option to tweet him came up when clicking the twitter link. In the meantime...

I found the site, https://onedoes.github.io/snapdrop/, which actually looks like an updated version of Snapdrop that isn't http://snapdrop.net. Though it does not seem to work either, you have the option to rename your device on the network, use a shortlink to connect, and under the "refresh" icon, it has a "server status". Right now, the status reads "down | onedoessnapdrop-server-alonfoqgzq.now.sh".

Is the server down because they're working on a new version? Either way, I wish there was a link on both platforms that has updates for stuff like this... It's been a week and I mean it when I say I've lost a noteworthy amount of productivity due to this.

**Comment by mtratchet16** [comment]
At this point (minutes later) I can't seem to gain access to the original snapdrop.net anymore via computer (though I can on mobile) and on the new link, the status keeps varying between "up," "unknown," and "down". Hopefully someone is on it now.

**Comment by douglasduteil** [comment]
:wave: @onedoes member here.
Our fork died long ago...
I'll be reviving it this weekend if I have time :crossed_fingers:

**Comment by JosephTico** [comment]
https://sharedrop.io is an alternative you can try for now

**Comment by RobinLinus** [comment]
Sorry! You guys maxed out the credit card connect to Snapdrop's AWS account :D 
I'm about to fix this...

**Comment by RobinLinus** [comment]
Snapdrop is up again! 
Again, sorry for the downtime :)

**Comment by Akryum** [comment]
@RobinLinus Maybe you should open a Github Sponsoring page to help you with server costs!

**Comment by JKJameson** [comment]
The site seems to be down more than it's up. Put it on a provider with unlimited bandwidth.

**Comment by scotty6719** [comment]
sight down just when i need it

**Comment by naren-nallapareddy** [comment]
This is a great idea but it down often. As someone else suggested please put up a github sponsoring page.
